Feature/cafeteria 1
teamSANDOL/tuk_sandol_team pull request #21
Opened 2024-05-27 05:33 UTC by Seokyoung-Hong

학식 관련 기능입니다.

- 학식 보기
- 학식 등록

2024-05-30 12:23 UTC, Cycrypto reviewed
1차 리뷰 (API)

2024-05-30 12:23 UTC, Cycrypto commented on sandol/app.py
> +from .api_server.utils import error_message
모듈 임포트에서 상대경로를 사용하셨는데, 이유가 있으실까요?
`sandol.api_server.meal`처럼 명확한 경로를 쓰는게 좋아보일거 같아서요..!

2024-05-30 12:23 UTC, Cycrypto commented on sandol/api_server/meal.py
> +)
여기도 마찬가지로 상대경로로 모듈을 import하고 있네요!

2024-05-30 12:23 UTC, Cycrypto commented on sandol/api_server/meal.py
> +    assert payload.detail_params is not None
이부분이 이해가 잘 가지 않네요. 추가적인 설명 부탁드립니다.
들어올 값이 None이 아님이 보장된다의 의미로 사용하신거라면 굳이 존재 이유가 궁금해서요!

2024-05-30 12:23 UTC, Cycrypto commented on sandol/api_server/meal.py
> +    assert payload.detail_params is not None
그게 아니라면 이에 대한 추가적인 예외처리가 필요하지 않나 싶습니다.

```python
    if payload.detail_params is None or "menu" not in payload.detail_params:
        return JSONResponse(
            meal_error_response_maker("메뉴 정보가 없습니다.").get_dict(),
            status_code=400
        )
```

2024-05-30 12:23 UTC, Cycrypto commented on sandol/api_server/meal.py
> +async def meal_delete(meal_type: str, request: Request):
meal_register, delete를 포함해 대부분 유사한 코드 흐름을 보이고 있습니다. 중복되는 코드가 많다는 의미인데, 따로 떼서 다른 모듈로 분리해보시는건 어떤가요? 예를들면 Payload 변환이나, 예외처리부분이라던가 그렇습니다.

2024-05-30 12:23 UTC, Cycrypto commented on sandol/api_server/utils.py
> +from ..crawler.ibookdownloader import BookDownloader
여기도..

2024-05-30 12:23 UTC, Cycrypto commented on sandol/api_server/utils.py
> +            description += f"{menu}\n"
```python
description = "\n".join(menu_list) if menu_list else "식단 정보가 없습니다."

```

2024-05-30 12:23 UTC, Cycrypto commented on sandol/api_server/utils.py
> +    return response
```python
response = KakaoResponse() + SimpleTextComponent("식단 정보 미리보기") + lunch + dinner
response.add_quick_replies(CAFETRIA_REGISTER_QUICK_REPLY_LIST)
return response
```
예시입니다.
조금 더 간소화가 가능할 거 같아요.

2024-05-30 12:23 UTC, Cycrypto commented on sandol/api_server/utils.py
> +def check_tip_and_e(func):
파일 경로와 수정시장 검증 로직을 함수로 분리하여 중복을 피할 수 있지 않을까 싶습니다

2024-06-01 09:48 UTC, Seokyoung-Hong reviewed
파이썬의 filter 함수를 사용할 수 있을것 같아요.

```python
self.tip_lunch_menu = list(filter(lambda menu: menu != '*복수메뉴*', self.tip_lunch_menu))
```

2024-06-01 09:48 UTC, Seokyoung-Hong commented on sandol/crawler/cafeteria.py
> +import os
모듈 docstring을 작성해 주세요. 간단하게 해당 모듈(파일)이 어떤 기능을 담고 있는지만 작성하면 됩니다.

2024-06-01 09:48 UTC, Seokyoung-Hong commented on sandol/crawler/cafeteria.py
> +class Restaurant:
클래스 docstring을 작성해 주세요. 우리는 google style을 따르기로 했으므로, 아래 첨부된 링크를 참조하면 좋을 것 같습니다.
[docstring ](https://yosseulsin-job.github.io/Google-Python-Style-Guide-kor/#s3.8)

2024-06-01 09:48 UTC, Seokyoung-Hong commented on sandol/crawler/cafeteria.py
> +            :param menu_type: 업데이트할 메뉴 시간정보 ("lunch" 또는 "dinner").
우리는 google style을 따르기로 했으므로, docstring을 google style로 변경해주세요.
[docstring ](https://yosseulsin-job.github.io/Google-Python-Style-Guide-kor/#s3.8)

2024-06-01 09:48 UTC, Seokyoung-Hong commented on sandol/crawler/__init__.py
> +def get_view(identification):
함수 위 주석 대신 docstring을 활용해 주세요

2024-06-01 09:48 UTC, Seokyoung-Hong commented on sandol/crawler/__init__.py
> +# registration 모듈에서 사용자가 직접 호출할 수 있는 함수 정의
불필요한 주석이므로 삭제해주세요.

2024-06-01 09:48 UTC, Seokyoung-Hong commented on sandol/crawler/cafeteria.py
> +            filename = os.path.join(current_dir, 'test.json')
한 파일 안에서, Queto(따옴표)는 일관적으로 사용해주세요.
' 만 사용하거나, "만 사용해주세요.

결정한 결과에 맞추어 파일 전체를 수정해야합니다!

2024-06-01 09:48 UTC, Seokyoung-Hong commented on sandol/crawler/cafeteria.py
> +                self.opening_time.append([start.strftime("%p %I:%M"), end.strftime("%I:%M")])
코드가 80자를 초과해요. append 내부를 줄바꿈 하는 것이 좋을 것 같아요.

2024-06-01 09:48 UTC, Seokyoung-Hong commented on sandol/crawler/cafeteria.py
> +        except FileNotFoundError:
이 경우에는,
```python
try:
    # Some code that may raise FileNotFoundError
except FileNotFoundError as exc:
    raise FileNotFoundError(f'{filename} 파일을 찾을 수 없습니다.') from exc
```

이런 식으로 
as exc와 from exc로 에러를 연장처리 하는 것이 좋습니다. (동일한 종류의 에러를 만드니까요!)

2024-06-01 09:48 UTC, Seokyoung-Hong commented on sandol/crawler/cafeteria.py
> +            json.dump(data, file, ensure_ascii=False, indent=4)                     # json data 한꺼번에 test.json으로 덮어씌우기
## 주석 작성 규칙

1. 주석은 코드 옆 2칸 뒤에 작성해주세요.
2. 주석이 코드와 연결되기 위해 고의적으로 떨어져야 하는 경우, 주석을 코드 옆에 작성하는 것이 아니라, 서로 연결되는 주석 내용을 한 번에 작성하는 것이 좋습니다.
3. 주석을 포함한 코드가 80자를 넘기지 않게 유의해야합니다!

### 예시 코드 및 주석

```python
for restaurant_data in data:
    if restaurant_data["name"] == self.name:  # 식당 검색
        restaurant_data["lunch_menu"] = self.submit_update_menu("lunch")  # 점심 메뉴 변경 사항 존재 시 submit
        restaurant_data["dinner_menu"] = self.submit_update_menu("dinner")  # 저녁 메뉴 변경 사항 존재 시 submit
        restaurant_data["registration_time"] = dt.datetime.now().isoformat()  # registration time update
        restaurant_data["opening_time"] = self.opening_time  # opening time update
        restaurant_data["price_per_person"] = self.price_per_person  # 가격 update
        restaurant_found = True
        break

if not restaurant_found:
    raise ValueError(f"레스토랑 '{self.name}'가 test.json 파일에 존재하지 않습니다.")

with open(filename, 'w', encoding='utf-8') as file:
    json.dump(data, file, ensure_ascii=False, indent=4)  # json data 한꺼번에 test.json으로 덮어씌우기
```

## 개선된 주석 작성 예시
주석이 코드와 연결되기 위해 고의적으로 떨어져야 하는 경우, 다음과 같이 주석을 한 번에 작성하는 것이 좋습니다:

```python
for restaurant_data in data:
    if restaurant_data["name"] == self.name:  # 식당 검색
        # 점심 및 저녁 메뉴 변경 사항 존재 시 submit
        restaurant_data["lunch_menu"] = self.submit_update_menu("lunch")
        restaurant_data["dinner_menu"] = self.submit_update_menu("dinner")

        # registration time, opening time, 가격 update
        restaurant_data["registration_time"] = dt.datetime.now().isoformat()
        restaurant_data["opening_time"] = self.opening_time
        restaurant_data["price_per_person"] = self.price_per_person
        
        restaurant_found = True
        break

if not restaurant_found:
    raise ValueError(f"레스토랑 '{self.name}'가 test.json 파일에 존재하지 않습니다.")

with open(filename, 'w', encoding='utf-8') as file:
    json.dump(data, file, ensure_ascii=False, indent=4)  # json data 한꺼번에 test.json으로 덮어씌우기
```
이렇게 하면 코드와 주석이 더 명확하게 구분되어 가독성이 향상됩니다.

2024-06-01 09:48 UTC, Seokyoung-Hong commented on sandol/crawler/cafeteria.py
> +            raise ValueError("temp_menu.json file doesn't exist")
파일 삭제가 목적인 코드에서 파일이 존재하지 않음에 대한 에러는 발생할 필요가 없을 것 같습니다.

2024-06-01 09:48 UTC, Seokyoung-Hong commented on sandol/crawler/cafeteria.py
> +        return (f"Restaurant: {self.name}, Lunch: {self.lunch}, Dinner: {self.dinner}, "
코드가 너무 깁니다. 코드 길이를 줄여주세요. 
 `(` 뒤에 값을 넣지 말고 바로 줄바꿈 할 수 있습니다.
```python
temp_data = ["data",
             "data2"]
```
대신,
```python
temp_data = [
    "data",
    "data2"
    ]
```
이렇게 할 수 있습니다.
물론 위의 방법도 틀린 방법은 아닙니다.

2024-06-01 09:48 UTC, Seokyoung-Hong commented on sandol/crawler/cafeteria.py
> +        self.save_temp_menu()
add_menu와 delete_menu 메서드의 코드가 거의 유사합니다. 이를 하나의 메서드로 통합하고, 추가나 삭제를 인자로 받아 처리하면 중복을 줄일 수 있습니다.

2024-06-01 09:48 UTC, Seokyoung-Hong commented on sandol/crawler/cafeteria.py
> +        return new_class(data["name"], data["lunch_menu"], data["dinner_menu"], data["location"], registration_time)
1. return 코드가 너무 길어요. 한 줄에 80자 이하로 작성해야 해요. 괄호를 씌워 줄바꿈을 하는 것이 좋을것 같아요.
2. new_class 대신, cls를 사용하는 것이 좋을 것 같아요.

2024-06-01 09:48 UTC, Seokyoung-Hong commented on sandol/crawler/cafeteria.py
> +        }
rest_info 메서드에서 레스토랑 정보가 하드코딩되어 있습니다. 이는 유지보수 시 불편할 수 있습니다. 이러한 데이터를 외부 JSON 파일이나 데이터베이스에서 불러오는 것이 좋습니다.
아니면, settings.py와 같은 상수 전용 관리 모듈을 이용하는 것이 좋습니다.

2024-06-01 09:48 UTC, Seokyoung-Hong commented on sandol/crawler/cafeteria.py
> +            time_slots = time_info.split(" / ")
type hint를 추가하는 것이 좋을 것 같아요!
이를 통해 `time_info.split(" / ")` 코드에서 linter의 도움을 받을 수 있고,
코드를 검증하기가 쉬워져요.

2024-06-01 09:48 UTC, Seokyoung-Hong commented on sandol/crawler/cafeteria.py
> +                break
이 if문의 각 라인에 대한 주석을 일반화하여 달 수 있을 것 같아요.
뿐만 아니라, 주석을 포함한 코드가 80자를 초과해서는 안돼요!
만약 주석으로 인해 80자를 초과한다면, 주석을 코드 위로 올릴 수 있어요.

2024-06-01 09:48 UTC, Seokyoung-Hong commented on sandol/crawler/cafeteria.py
> +                data = json.load(file)
이 코드가 클래스 전체에서 반복되는 것을 확인했어요.
GPT는 아래와 같이 static method를 추가해 처리하는 것을 추천해요!

```python
    @staticmethod
    def get_file_path(filename):
        """
        주어진 파일 이름에 대한 절대 경로를 반환하는 유틸리티 함수
        """
        current_dir = os.path.dirname(__file__)
        return os.path.join(current_dir, filename)

    @staticmethod
    def load_json_file(filename):
        """
        JSON 파일을 읽어오는 유틸리티 함수
        """
        filepath = Restaurant.get_file_path(filename)
        try:
            with open(filepath, 'r', encoding='utf-8') as file:
                return json.load(file)
        except (json.decoder.JSONDecodeError, FileNotFoundError):
            raise FileNotFoundError(f"{filename} 파일을 찾을 수 없습니다.")

    @staticmethod
    def save_json_file(data, filename):
        """
        데이터를 JSON 파일로 저장하는 유틸리티 함수
        """
        filepath = Restaurant.get_file_path(filename)
        with open(filepath, 'w', encoding='utf-8') as file:
            json.dump(data, file, ensure_ascii=False, indent=4)
```

2024-06-01 09:48 UTC, Seokyoung-Hong commented on sandol/crawler/cafeteria.py
> +            raise ValueError(f"레스토랑 '{self.name}'에 대한 정보를 찾을 수 없습니다.")
1. opening_time을 문자열로 저장하고 있는데, 이를 datetime객체로 저장하면 클래스를 더 잘 활용할 수 있을 것 같아요.
또한, `@property` decorator를 이용해 lunch_time_str, dinner_time_str 같은 메서드를 str으로 반환하도록 하면 더욱 더 유용할 수 있어요. (API 팀의 요구사항이 아닌 단순 리뷰 및 제안입니다.)
2. GPT는 시간 분석을 메서드 또는 함수로 분리하는 것을 추천해요. 이렇게 하면, 반환 형식이 어떻게 될지 더욱더 쉽게 이해할 수 있을것 같아요.
```python
def parse_time(self, time_str):
        """
        시간 문자열을 datetime.time 객체로 변환하는 메서드
        """
        time_str = time_str.strip().replace('시', ':').replace('분', '')
        if '오전' in time_str:
            time_str = time_str.replace('오전', 'AM ')
        elif '오후' in time_str:
            time_str = time_str.replace('오후', 'PM ')

        if ':' not in time_str.split()[1]:
            time_str += ':00'

        return dt.datetime.strptime(time_str, '%p %I:%M').time()
```

2024-06-01 09:48 UTC, Seokyoung-Hong commented on sandol/crawler/ibookcrawler.py
> +        self.price_per_person = 6500
이 부분은 settings.py로 옮길 수 잇을 것 같아요.

2024-06-01 09:48 UTC, Seokyoung-Hong commented on sandol/api_server/utils.py
> +    return response
리뷰 감사합니다. 피드백을 반영하여 코드를 수정했습니다.
하지만, add_quick_replies 메서드가 kakao 라이브러리에 존재하지 않아, 퀵리플라이에 대한 반복문은 수정되지 못했습니다.

2024-06-01 09:48 UTC, Seokyoung-Hong commented on sandol/api_server/utils.py
> +            description += f"{menu}\n"
리뷰 감사합니다. 피드백을 반영하여 코드를 수정했습니다.

2024-06-01 09:48 UTC, Seokyoung-Hong commented on sandol/app.py
> +from .api_server.utils import error_message
리뷰 감사합니다. 피드백을 반영하여 코드를 수정했습니다.
- 처음 코드를 작성할 때, app.py의 위치와 베포시 폴더 구조를 명확히 인지하지 못해서 구조의 수정을 염두하고 상대경로로 코드작성을 시작했습니다. 하지만 이제 코드 구조의 틀이 잡혔기 때문에 절대경로로 수정했습니다.

2024-06-01 09:48 UTC, Seokyoung-Hong commented on sandol/api_server/meal.py
> +)
리뷰 감사합니다. 피드백을 반영하여 코드를 수정했습니다.

2024-06-01 09:48 UTC, Seokyoung-Hong commented on sandol/api_server/meal.py
> +async def meal_delete(meal_type: str, request: Request):
리뷰 감사합니다. 피드백을 반영하여 코드를 수정했습니다.

이 부분을 발견하고 수정하려고 시도했으나 view와 register를 함께 통합해서 중복을 제거하려니 payload 변환을 제외하면 중복이 딱히 제거되는 것이 없어서 포기했습니다.
하지만 피드백 덕분에, register에서는 중복을 다수 줄일 수 있음을 확인하였고 수정했습니다.

- get_payload_and_restaurant 함수 추가, 해당함수는 API 로직과 밀접하게 연관되며, 해당 파일 외에서는 사용되지 않으며, utils.py의 다른 함수들과 다르게 FastAPI의 Request 객체 의존성이 있기 때문에 utils.py 대신, meal.py 함수에 작성하였습니다.

2024-06-01 09:48 UTC, Seokyoung-Hong commented on sandol/api_server/utils.py
> +from ..crawler.ibookdownloader import BookDownloader
리뷰 감사합니다. 피드백을 반영하여 코드를 수정했습니다.

2024-09-24 01:26 UTC, Cycrypto requested changes
확인했습니다

2024-09-24 01:26 UTC, Cycrypto commented on sandol/api_server/meal.py
> +
여기도 테스트가 제거된 상태인가요

2024-09-24 01:26 UTC, Cycrypto commented on sandol/api_server/meal.py
> +            print("등록시간에 시간대 정보가 없어 9시간을 더해 KST로 변환합니다.")
print를 대체할 수 있는 방법이 있을거 같아요

2024-09-24 01:26 UTC, Cycrypto commented on sandol/api_server/meal.py
> +            message_text="테스트 학식",  # TODO(Seokyoung_Hong): 베포 시 '테스트' 제거
제거가 되어야 하는 부분인가요

2024-09-24 01:26 UTC, Cycrypto commented on sandol/api_server/meal.py
> +        message_text=f"테스트 학식 {restaurant_name}"
여기도입니다

2024-09-24 01:26 UTC, Cycrypto commented on sandol/api_server/settings.py
> +    "산돌식당": "https://naver.me/xEMZ6QdE",
이것도 제거가 되어야 하는부분인가요

2024-09-24 01:26 UTC, Cycrypto commented on sandol/api_server/utils.py
> +            traceback.format_tb(message.__traceback__))
이부분도 처리가 안되어있는거 같아요

2024-09-24 01:26 UTC, Cycrypto commented on sandol/api_server/utils.py
> +            f"트레이스백:\n{exception_traceback}"  # TODO(Seokyoung_Hong): 베포시 주석 처리
동일합니다

2024-09-24 01:26 UTC, Cycrypto commented on sandol/bucket/common.py
> +FILE_KEY = "test.json"
파일 명 변경이 필요해보입니다. 혹시 권한이 없으시면 말씀해주세요

2024-09-24 01:26 UTC, Cycrypto commented on sandol/crawler/test.json
> +[
아 test.json을 원래 s3에 있는 파일명으로 변경하셔야 할거 같네요..!

2024-09-24 10:20 UTC, Seokyoung-Hong commented
현재 카카오톡 오픈빌더에서는 '학식'과 같은 의도된 발화 앞에 '테스트'라는 문구가 추가되도록 설정되어 있습니다. 이는 기존 '학식' 블록과 스킬을 변경하지 않고, 별도의 블록과 스킬로 개발하기 위해서입니다.

이에 맞춰 PR에 올린 코드에서도 '테스트 학식' 발화를 이용해 동작하도록 설정했습니다. 코드 리뷰 이후, 해당 코드를 배포 가능한 상태로 수정하였습니다.

다만, 카카오톡 오픈빌더 설정은 이번에 수정하지 않았으며, 실제 배포 시에는 오픈빌더 설정을 수정 및 배포해야 합니다.

2024-09-26 07:13 UTC, Cycrypto approved these changes

2024-09-26 07:13 UTC, merged